language: elixir

elixir:
  - 1.4.4
otp_release:
  - 19.3

env:
  - EVENT_STORE_VERSION='14.04-v4.0.1'

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"

before_install:
  - wget http://download.geteventstore.com/binaries/EventStore-OSS-Ubuntu-${EVENT_STORE_VERSION}.tar.gz
  - tar xf EventStore*.tar.gz
  - cd EventStore* && ./run-node.sh --run-projections=all --start-standard-projections=true --mem-db 2>&1> eventstore.log &

after_scripts:
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
