language: elixir

elixir:
  - 1.5.2
otp_release:
  - 20.1

env:
  - ES_VERSION=3
  - ES_VERSION=4

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"

before_install:
  - wget https://eventstore.org/downloads/EventStore-OSS-Ubuntu-${EVENT_STORE_VERSION}.tar.gz
  - tar xf EventStore*.tar.gz
  - cd EventStore* && ./run-node.sh --run-projections=all --start-standard-projections=true --mem-db 2>&1> eventstore.log &

after_scripts:
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
